version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mkulima-backend
    restart: always
    env_file: ./backend/.env.production
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mkulima-frontend
    restart: always
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: mkulima-db
    restart: always
    environment:
      POSTGRES_USER: mkulima
      POSTGRES_PASSWORD: mkulima123
      POSTGRES_DB: mkulima_market
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: mkulima-redis
    restart: always
    ports:
      - "6379:6379"

  proxy:
    image: nginx:stable
    container_name: mkulima-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  certs:
