version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mkulima
      POSTGRES_PASSWORD: mkulima_pass
      POSTGRES_DB: mkulima_market
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://mkulima:mkulima_pass@postgres:5432/mkulima_market
      JWT_SECRET: supersecretkey
      MPESA_CONSUMER_KEY: test_key
      MPESA_CONSUMER_SECRET: test_secret
      MPESA_SHORTCODE: 123456
      MPESA_PASSKEY: test_passkey
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
